### ISSUE TITLE
missing dependencies ? 

### ISSUE THREAD

**Issue by vqoph** [maxisam/angular-bootstrap-affix#11]
i have this error when I install the script using bower : 
```
 Failed to instantiate module mgcrea.bootstrap.affix due to:
Error: [$injector:modulerr] Failed to instantiate module mgcrea.jquery due to:
Error: [$injector:nomod] Module 'mgcrea.jquery' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

**Comment by vqoph** [comment]
it's look like a wiredep error, jquery-angular seems to be ignored by wiredep

**Comment by vqoph** [comment]
solved by adding this in my bower.json overrides
```
"angular-jquery": {
      "main": [
        "dist/angular-jquery.js"
      ]
    }
```

**Comment by atefBB** [comment]
I have the some issue but I don't use bower to manage dependencies, any ideas to solve it?

**Comment by vqoph** [comment]
@atefBB you can install angular-jquery manually as explained in the [README](https://github.com/maxisam/angular-bootstrap-affix/blob/master/README.md)

**Comment by atefBB** [comment]
thx @vqoph. 
SOLVED !

**Comment by AppDevGuy** [comment]
@vqoph This is not solved at all. You have made an exception for a library when the library needs to comply with the project it's being installed into. It's great that you solved your own issue but I will reopen this. The best solution would be for @maxisam to resolve the issue or someone with understanding of why/what `mcgrea.jquery` is and install it when installing this package.
