### ISSUE TITLE
Affix destroy method

### ISSUE THREAD

**Issue by rajamuthur** [maxisam/angular-bootstrap-affix#13]
I can able to destroy affix by using 
[Working Fine]
$(window).off('.affix');
$([selector]).removeData('affix').removeClass('affix affix-top affix-bottom');

But, unable to enable affix for same element 
[Not working]
$(window).on('.affix');
$([selector]).affix({
			offset: {
			   top: function () {
	   			return $([selector]).position().top;
			   }
		   }
	   });

Is there any specific way to destroy/disable affix for specific element ?
Thanks in advance.

**Comment by iqbalbary** [comment]
You can destroy affix with

`$(window).off('.affix')`
`$([selector]).removeData('bs.affix').removeClass('affix affix-top affix-bottom')`

And Start again with

`$([selector]).affix()`
