### ISSUE TITLE
Affix does not preserve width

### ISSUE THREAD

**Issue by rjmveloso** [maxisam/angular-bootstrap-affix#14]
Block loses width when affix is set.
I was trying to use this module instead of angular-strap, its smaller and does exactly what I need without a bunch of other dependencies, but I got this problem that is not happening in angular-strap.
I have a requirement to affix a lot of block, some of them in the same page and is an additional effort to set width in specific CSS classes.

Can this be considered an improvement?

**Comment by maxisam** [comment]
sorry, this project is no longer maintained. But you are welcome to make a pull request. I will merge it.
