### ISSUE TITLE
Feature request: Disable when list grows too long

### ISSUE THREAD

**Issue by sDaniel** [maxisam/angular-bootstrap-affix#9]
When the affixed list grows too long for the display hight the user wont be able to see the last or first elements. To reproduce a similar effect simply go to http://getbootstrap.com/components/ resize the window to be small and try to read the right sidebar.

It would be nice to (optionally) check for this and then disable affix.

**Comment by maxisam** [comment]
I don't think I will add more feature to this but you are welcome to make a
pull request.

**Comment by sDaniel** [comment]
OK thanks for the quick response. It's not a requirenment in my current project but if should build it I'll post a pull request.

**Comment by WENWUMAO** [comment]
Hey, I folked the sources and made changes to solve the issue that last part cannot be shown when list grows too long.

**Comment by maxisam** [comment]
Great ! if you can make a pull request I would merge it.

**Comment by MikiSoft** [comment]
@WENWUMAO will you make a pull request to be merged with this main repository?

**Comment by WENWUMAO** [comment]
@MikiSoft  I just made the pull request :D

**Comment by maxisam** [comment]
Thank you !!!
